### ISSUE TITLE
Dockerfile issues with misp-modules

### ISSUE THREAD

**Issue by execgit** [xme/misp-docker#17]
Installing misp-modules does not work currently. The modules need newer versions of requests and urllib3 than currently provided by Ubuntu.

I remediated this with adding
```
pip3 install --upgrade --ignore-installed urllib3 && \
pip3 install --upgrade --ignore-installed requests
```
to the dockerfile before installing misp-modules. This is probably not the optimal solution, though.

**Comment by execgit** [comment]
This was before the latest updates. Need to test with the latest version, sorry about that.

**Comment by xme** [comment]
I added them just to be sure, thank for the tests!

/x
