### ISSUE TITLE
misp-web cannot connect to misp-db container

### ISSUE THREAD

**Issue by VictorCovalski** [xme/misp-docker#20]
Hi, I've built the docker image following the instructions on the readme.
The following error occurs when I try to run docker-compose up.

docker-compose up
Recreating misp-db
Recreating misp-web
Attaching to misp-db, misp-web
misp-web    | Container started for the fist time. Setup might time a few minutes. Please wait...
misp-web    | (Details are logged in /tmp/install.log)
misp-web    | Configuring postfix
misp-web    | 
misp-web    | Current default time zone: 'Etc/UTC'
misp-web    | Local time is now:      Thu Jul  6 15:39:11 UTC 2017.
misp-web    | Universal Time is now:  Thu Jul  6 15:39:11 UTC 2017.
misp-web    | 
misp-web    | Creating MySQL database
misp-web    | MYSQL_ROOT_PASSWORD is set to 'SomeRandomPassword123!'
misp-web    | MYSQL_MISP_PASSWORD is set to 'SomeRandomPassword123!'
misp-web    | mysql: [Warning] Using a password on the command line interface can be insecure.
misp-web    | ERROR 1130 (HY000): Host '172.18.0.3' is not allowed to connect to this MySQL server
misp-web exited with code 1

**Comment by spacepatcher** [comment]
@VictorCovalski 
Had the same problem. My solution to the problem:
(in mysql console from database root user)
```
> USE mysql;
> UPDATE user SET host='%' WHERE host='localhost';
> FLUSH PRIVILEGES;
```
By default, MySQL root user is not allowed to login from external hosts.

**Comment by giomke** [comment]
I had similar problem but now how i can connect to the web?
![screenshot-2018-1-8 xme misp-docker](https://user-images.githubusercontent.com/19889044/34683664-22b381fe-f4bc-11e7-9dac-cbe0f2028072.png)
![1](https://user-images.githubusercontent.com/19889044/34683672-2c530720-f4bc-11e7-81c8-3f25f926d918.png)
