### ISSUE TITLE
No longer builds

### ISSUE THREAD

**Issue by alecisec** [xme/misp-docker#24]
Build started failing in the last couple of days -

`Step 55/136 : RUN php composer.phar install -vv
 ---> Running in 04ef8987eed0
Loading composer repositories with package information
Updating dependencies (including require-dev)

  [Composer\Downloader\TransportException]
  Content-Length mismatch

Exception trace:
 () at phar:///var/www/MISP/app/composer.phar/src/Composer/Util/RemoteFilesystem.php:294
 Composer\Util\RemoteFilesystem->get() at phar:///var/www/MISP/app/composer.phar/src/Composer/Util/RemoteFilesystem.php:101
 Composer\Util\RemoteFilesystem->getContents() at phar:///var/www/MISP/app/composer.phar/src/Composer/Repository/ComposerRepository.php:646
 Composer\Repository\ComposerRepository->fetchFile() at phar:///var/www/MISP/app/composer.phar/src/Composer/Repository/ComposerRepository.php:558
 Composer\Repository\ComposerRepository->loadProviderListings() at phar:///var/www/MISP/app/composer.phar/src/Composer/Repository/ComposerRepository.php:289
 Composer\Repository\ComposerRepository->whatProvides() at phar:///var/www/MISP/app/composer.phar/src/Composer/DependencyResolver/Pool.php:204
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///var/www/MISP/app/composer.phar/src/Composer/DependencyResolver/Pool.php:193
 Composer\DependencyResolver\Pool->whatProvides() at phar:///var/www/MISP/app/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php:168
 Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage() at phar:///var/www/MISP/app/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php:322
 Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at phar:///var/www/MISP/app/composer.phar/src/Composer/DependencyResolver/Solver.php:214
 Composer\DependencyResolver\Solver->solve() at phar:///var/www/MISP/app/composer.phar/src/Composer/Installer.php:461
 Composer\Installer->doInstall() at phar:///var/www/MISP/app/composer.phar/src/Composer/Installer.php:216
 Composer\Installer->run() at phar:///var/www/MISP/app/composer.phar/src/Composer/Command/InstallCommand.php:135
 Composer\Command\InstallCommand->execute() at phar:///var/www/MISP/app/composer.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///var/www/MISP/app/composer.phar/vendor/symfony/console/Application.php:847
 Symfony\Component\Console\Application->doRunCommand() at phar:///var/www/MISP/app/composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///var/www/MISP/app/composer.phar/src/Composer/Console/Application.php:231
 Composer\Console\Application->doRun() at phar:///var/www/MISP/app/composer.phar/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///var/www/MISP/app/composer.phar/src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar:///var/www/MISP/app/composer.phar/bin/composer:43
 require() at /var/www/MISP/app/composer.phar:24

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

ERROR: Service 'misp' failed to build: The command '/bin/sh -c php composer.phar install -vv' returned a non-zero code: 1`

**Comment by alecisec** [comment]
note : I changed line 77 in https://github.com/xme/misp-docker/blob/master/Dockerfile to add '-vv' to provide verbose logs.

**Comment by alecisec** [comment]
Tried again with a clean pull -- slightly different error, same cause I'd imagine

Step 47/121 : RUN php composer.phar install -vv
 ---> Running in ac95a3ca46fc
Loading composer repositories with package information
Updating dependencies (including require-dev)
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info


  [ErrorException]
  zlib_decode(): data error


Exception trace:
 () at phar:///var/www/MISP/app/composer.phar/src/Composer/Util/RemoteFilesystem.php:388
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 zlib_decode() at phar:///var/www/MISP/app/composer.phar/src/Composer/Util/RemoteFilesystem.php:388
 Composer\Util\RemoteFilesystem->get() at phar:///var/www/MISP/app/composer.phar/src/Composer/Util/RemoteFilesystem.php:101
 Composer\Util\RemoteFilesystem->getContents() at phar:///var/www/MISP/app/composer.phar/src/Composer/Repository/ComposerRepository.php:646
 Composer\Repository\ComposerRepository->fetchFile() at phar:///var/www/MISP/app/composer.phar/src/Composer/Repository/ComposerRepository.php:558
 Composer\Repository\ComposerRepository->loadProviderListings() at phar:///var/www/MISP/app/composer.phar/src/Composer/Repository/ComposerRepository.php:289
 Composer\Repository\ComposerRepository->whatProvides() at phar:///var/www/MISP/app/composer.phar/src/Composer/DependencyResolver/Pool.php:204
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///var/www/MISP/app/composer.phar/src/Composer/DependencyResolver/Pool.php:193
 Composer\DependencyResolver\Pool->whatProvides() at phar:///var/www/MISP/app/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php:168
 Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage() at phar:///var/www/MISP/app/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php:322
 Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at phar:///var/www/MISP/app/composer.phar/src/Composer/DependencyResolver/Solver.php:214
 Composer\DependencyResolver\Solver->solve() at phar:///var/www/MISP/app/composer.phar/src/Composer/Installer.php:461
 Composer\Installer->doInstall() at phar:///var/www/MISP/app/composer.phar/src/Composer/Installer.php:216
 Composer\Installer->run() at phar:///var/www/MISP/app/composer.phar/src/Composer/Command/InstallCommand.php:135
 Composer\Command\InstallCommand->execute() at phar:///var/www/MISP/app/composer.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///var/www/MISP/app/composer.phar/vendor/symfony/console/Application.php:847
 Symfony\Component\Console\Application->doRunCommand() at phar:///var/www/MISP/app/composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///var/www/MISP/app/composer.phar/src/Composer/Console/Application.php:231
 Composer\Console\Application->doRun() at phar:///var/www/MISP/app/composer.phar/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///var/www/MISP/app/composer.phar/src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar:///var/www/MISP/app/composer.phar/bin/composer:43
 require() at /var/www/MISP/app/composer.phar:24

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

ERROR: Service 'misp-web' failed to build: The command '/bin/sh -c php composer.phar install -vv' returned a non-zero code: 1

**Comment by alecisec** [comment]
seems to be working today?

**Comment by kdeltared** [comment]
Hi,

I'm having the same error with a fresh new clone.
```
Step 47/121 : RUN php composer.phar install
 ---> Running in 342bea151d4b
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pear/crypt_gpg v1.4.0 requires pear/console_commandline * -> satisfiable by pear/console_commandline[dev-master, v1.2.1, v1.2.2].
    - pear/crypt_gpg v1.4.1 requires pear/console_commandline * -> satisfiable by pear/console_commandline[dev-master, v1.2.1, v1.2.2].
    - pear/crypt_gpg v1.4.2 requires pear/console_commandline * -> satisfiable by pear/console_commandline[dev-master, v1.2.1, v1.2.2].
    - pear/crypt_gpg v1.4.3 requires pear/console_commandline * -> satisfiable by pear/console_commandline[dev-master, v1.2.1, v1.2.2].
    - pear/crypt_gpg v1.6.0 requires pear/console_commandline * -> satisfiable by pear/console_commandline[dev-master, v1.2.1, v1.2.2].
    - pear/crypt_gpg v1.6.1 requires pear/console_commandline * -> satisfiable by pear/console_commandline[dev-master, v1.2.1, v1.2.2].
    - pear/crypt_gpg v1.6.2 requires pear/console_commandline * -> satisfiable by pear/console_commandline[dev-master, v1.2.1, v1.2.2].
    - pear/console_commandline v1.2.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - pear/console_commandline v1.2.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - pear/console_commandline dev-master requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - Installation request for pear/crypt_gpg @stable -> satisfiable by pear/crypt_gpg[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.6.0, v1.6.1, v1.6.2].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-igbinary.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-mbstring.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-redis.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
ERROR: Service 'misp-web' failed to build: The command '/bin/sh -c php composer.phar install' returned a non-zero code: 2

```

**Comment by StephenThomson** [comment]
I also have this error.

**Comment by xme** [comment]
Closed. See [#25](https://github.com/xme/misp-docker/issues/25)
