### ISSUE TITLE
'misp-objects' already exists

### ISSUE THREAD

**Issue by pwlgrzs** [xme/misp-docker#26]
Getting this when building:

Step 80/129 : RUN git clone https://github.com/MISP/misp-objects.git
 ---> Running in 409e08c4f2c4
fatal: destination path 'misp-objects' already exists and is not an empty directory.
The command '/bin/sh -c git clone https://github.com/MISP/misp-objects.git' returned a non-zero code: 128

Is there any quick fix? Thanks!

**Comment by pwlgrzs** [comment]
I've added temporary workaround (added other folders too as it was stopping there):
`RUN rm -rm misp-objects misp-galaxy taxonomies warninglists`

but I don't think this is expected behaviour.

**Comment by xme** [comment]
This project has been integrated into the official MISP repository:
https://github.com/MISP/misp-docker/
