### ISSUE TITLE
Compose pulls incompatible MySQL version.

### ISSUE THREAD

**Issue by strfx** [xme/misp-docker#27]
MISP does not seem to work with the recently released MySQL 8.0 GA. Running docker-compose, as described, will yield an error:
```
Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
```

The compose file will pull the latest version of mysql, which has been changed to 8.0 (from 5.7). Pinning the version to 5.7 solves the issue.

**Comment by xme** [comment]
My Docker setup has been integrated into the official MISP repository. I fixed the Dockerfile to pin to a compatible version. See https://github.com/MISP/misp-docker/
