### ISSUE TITLE
ubuntu:latest does not support php5

### ISSUE THREAD

**Issue by jeromekleinen** [xme/misp-docker#3]
Hello Xavier,

I've recently built your MISP Docker container, but after the 16.04 update of ubuntu, ubuntu:latest is currently not the most suitable base as they upgraded from php5 to php7. The main problem is that Redis is not officially supported yet for php7 and I am not sure whether the application itself works nicely in php7. Finally some config paths have changed in php7.

I am using ubuntu:trusty as base image and that seems to work fine!

Thx for the Dockerfile!

**Comment by MattCarothers** [comment]
The newest pecl redis package also requires php7, which causes the build to die.  I got it to build by specifying an older version:

RUN pecl install redis-2.2.8

**Comment by dmblack** [comment]
Found myself here after an article on ycombinator.

I also had issues with PHP;

```
docker build -t misp/misp --build-arg MYSQL_ROOT_PASSWORD=example .
```

During prep, step 12:

> E: Package 'libapache2-mod-php5' has no installation candidate
> E: Package 'php5-gd' has no installation candidate
> E: Package 'php5-mysql' has no installation candidate
> E: Package 'php5-dev' has no installation candidate

Following jksecurity's proposal of running ubuntu:trusty; I was able to get get past this stage.

Dockerfile;
`FROM ubuntu`
to
`FROM ubuntu:trusty`

However; still build issues. See [https://github.com/xme/misp-docker/issues/4](https://github.com/xme/misp-docker/issues/4)
